# Default values for cytomine.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#
# Services - these are the services deployed by this chart
#

memcached:
  port: 11211
  image:
    pullPolicy: IfNotPresent
    repository: cytomine/memcached
    tag: v1.1.2
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "500m"

rabbitmq:
  port: 5672
  managementPort: 15672
  password: router
  image:
    pullPolicy: IfNotPresent
    repository: cytomine/rabbitmq
    tag: v1.1.2

postgresql:
  image:
    pullPolicy: IfNotPresent
    repository: cytomine/postgis
    tag: v2.0.0

nginx:
  port: 80
  image:
    pullPolicy: IfNotPresent
    repository: cytomine/nginx
    tag: v1.3.1

web_ui:
  port: 8080
  image:
    pullPolicy: IfNotPresent
    repository: cytomine/web_ui
    tag: v1.2.1

#
# Kuberenetes things - these are help make the debugging and administrating of
#                      the deployment easier.
#

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname
  # template
  name: ""
