apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "cytomine.name" . }}-image-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.imageStorage }}
