apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "cytomine.name" . }}-singularity-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.singularityStorage }}
