{{ if .Values.ims.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cytomine.name" . }}-ims
  labels:
    role: ims
    app: {{ include "cytomine.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Release.Name }}-ims
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "cytomine.name" . }}-ims
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        role: ims
        app: {{ template "cytomine.name" . }}-ims
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "cytomine.serviceAccountName" . }}
      volumes:
        - name: images
          persistentVolumeClaim:
            claimName: {{ template "cytomine.name" . }}-image-claim
      containers:
        - name: {{ .Chart.Name }}-ims
          image: "{{ .Values.ims.image.repository }}:{{ .Values.ims.image.tag }}"
          imagePullPolicy: {{ .Values.ims.image.pullPolicy }}
          volumeMounts:
            - name: images
              mountPath: "/data/images"
          env:
          - name: IMS_STORAGE_PATH
            value: /data/images
          resources:
            {{- toYaml .Values.ims.resources | nindent 12 }}
{{ end }}
