{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cytomine.serviceAccountName" . }}
  labels:
    {{- include "cytomine.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: job-creator
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "watch", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: create-jobs
subjects:
- kind: ServiceAccount
  name: {{ include "cytomine.serviceAccountName" . }}
  apiGroup: ""
roleRef:
  kind: Role
  name: job-creator
  apiGroup: ""
{{- end }}
