apiVersion: v1
kind: Service
metadata:
  name: {{ include "cytomine.name" . }}-web-ui
spec:
  selector:
    app: {{ include "cytomine.name" . }}-web-ui
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
